
services:
  mysql-invoice:
    container_name: mysql-invoice
    image: 'mysql:8.0'
    environment:
      MYSQL_ROOT_PASSWORD: password #$MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: main #$MYSQL_DATABASE
    ports:
      - '3306:3306'
    expose:
      - 3306
    volumes:
      - ./datadir/dev:/var/lib/mysql
    networks:
      - internalnet
  phpmyadmin-invoice:
    image: phpmyadmin/phpmyadmin
    container_name: pma-invoice
    depends_on:
      - mysql-invoice
    links:
      - mysql-invoice
    environment:
      PMA_HOST: mysql-invoice
      MYSQL_USER: root #$MYSQL_USER
      MYSQL_PASSWORD: password #$MYSQL_PASSWORD
      DB_DATABASE: main #$MYSQL_DATABASE
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: unless-stopped
    ports:
      - 8081:80
    networks:
      - internalnet
  
  express-app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
    command: node index.js
    networks:
      - internalnet
      
networks:
  internalnet:
    driver: bridge

volumes:
  db_data:
  node_modules: